import '@/styles/globals.css'

import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'

import { cn } from '@/lib/utils'
import { ProviderNextAuth } from '@/providers/next-auth'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen w-full max-w-full bg-background font-sans antialiased',
          fontSans.variable,
        )}
      >
        <ProviderNextAuth>{children}</ProviderNextAuth>
      </body>
    </html>
  )
}
